### ISSUE TITLE
Couldn't find preset "es2015" && "stage-0" relative to directory "~/project/node_modules/linkstate"

### ISSUE THREAD

**Issue by gazedash** [developit/linkstate#13]
### Expected behavior:
Doesn't require any babel plugins

### Actual behavior:
Throws errors, requires "es2015" and "stage-0" babel config.

### Steps to reproduce
```
git clone https://github.com/parcel-bundler/examples
cd examples/preact
yarn
yarn add linkstate
# add some code using linkstate
yarn start
```

```
  /home/dalvik/WebstormProjects/preact-parcel/node_modules/linkstate/dist/linkstate.es.js: Couldn't find preset "es2015" relative to directory "/home/dalvik/WebstormProje🚨  
```

```
🚨  /home/dalvik/WebstormProjects/preact-parcel/node_modules/linkstate/dist/linkstate.es.js: Couldn't find preset "stage-0" relative to directory "/home/dalvik/WebstormProjcts/preact-parcel/node_modules/linkstate"
    at /home/dalvik/WebstormProjects/preact-parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/dalvik/WebstormProjects/preact-parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/dalvik/WebstormProjects/preact-parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/dalvik/WebstormProjects/preact-parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/dalvik/WebstormProjects/preact-parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/dalvik/WebstormProjects/preact-parcel/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/dalvik/WebstormProjects/preact-parcel/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.getParserOptions (/home/dalvik/WebstormProjects/preact-parcel/node_modules/parcel-bundler/src/assets/JSAsset.js:60:20)
    at JSAsset.parse (/home/dalvik/WebstormProjects/preact-parcel/node_modules/parcel-bundler/src/assets/JSAsset.js:68:32)
```

**Comment by developit** [comment]
This is parcel issue.

**Comment by Depender-Sethi** [comment]
**npm i -D babel-preset-env** (if you haven't)
**npm i -D babel-preset-stage-0**

and your webpack config - **presets: ['env']**
(as shown in the image below)

![image](https://user-images.githubusercontent.com/32180131/38052934-4a54603a-32f0-11e8-806f-2b1a36eb7cfd.png)

**Comment by davidgaldon** [comment]
@Depender-Sethi That doesn't fix the issue for me.

This is my full error:

ERROR in ./node_modules/linkstate/dist/linkstate.es.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "es2015" relative to directory "/Users/dgaldon/Documents/DGH/MyApps/Preact1/node_modules/linkstate"
    at /Users/dgaldon/Documents/DGH/MyApps/Preact1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/dgaldon/Documents/DGH/MyApps/Preact1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/dgaldon/Documents/DGH/MyApps/Preact1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/dgaldon/Documents/DGH/MyApps/Preact1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/dgaldon/Documents/DGH/MyApps/Preact1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/dgaldon/Documents/DGH/MyApps/Preact1/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/dgaldon/Documents/DGH/MyApps/Preact1/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/dgaldon/Documents/DGH/MyApps/Preact1/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/dgaldon/Documents/DGH/MyApps/Preact1/node_modules/babel-loader/lib/index.js:50:20)
 @ ./src/components/Form.js 12:17-37
 @ ./src/components/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src
